[package]
name = "tin-summer"
version = "1.12.0"
authors = ["Vanessa McHale <vanessa.mchale@reconfigure.io>"]
license-file = "LICENSE"
description = "Command-line tool to find build artifacts and thing occupying space on your computer. Shatters records not glass."
readme = "README.md"
repository = "https://nest.pijul.com/vamchale/tin-summer"
documentation = "https://github.com/vmchale/tin-summer#README"
homepage = "https://github.com/vmchale/tin-summer"

#build = "build.rs"

#[build-dependencies]
#clap = {version = "2.25", features = ["yaml"]}

[profile.release]
lto = true

[features]
default = ["english"]
english = []
deutsch = []
francais = []
bash = []
fish = []
verbose = []

[dependencies]
num_cpus = "1.6"
walkdir = "1.0"
nom = "3.1"
colored = "1.5"
clap = {version = "2.25", features = ["yaml"]}
regex = "0.2"
pad = "0.1"
lazy_static = "0.2"
crossbeam = "0.2"
glob = "0.2"

[lib]
path = "src/lib.rs"
name = "liboskar"

[[bin]]
path = "src/main.rs"
name = "sn"
