[package]
name = "file-sniffer"
version = "0.1.0"
authors = ["Vanessa McHale <vamchale@gmail.com>"]

[dependencies]
colored = "1.5"
clap = {version = "2.24", features = ["yaml"]}
pad = "0.1"
regex = "0.2"

[lib]
path = "src/lib.rs"
name = "libsniff"

[[bin]]
path = "src/main.rs"
name = "sniff"
