[package]
name = "tin-summer"
version = "1.0.2-pre"
authors = ["Vanessa McHale <vanessa.mchale@reconfigure.io>"]
license-file = "LICENSE"
description = "Command-line tool to find build artifacts and junk on your computer. Shatters records not glass."
readme = "README.md"
repository = "https://nest.pijul.com/vamchale/file-sniffer"
documentation = "https://github.com/vmchale/tin-summer#README"
homepage = "https://github.com/vmchale/tin-summer" # consider hosting on http://vmchale.com/ ?

build = "build.rs"

[build-dependencies]
clap = {version = "2.24", features = ["yaml"]}

[profile.release]
lto = true

[features]
default = ["english"]
english = []
deutsch = []
francais = []
bash = []
fish = []
verbose = []

[dependencies]
nom = "3.0"
colored = "1.5"
clap = {version = "2.24", features = ["yaml"]}
regex = "0.2"
pad = "0.1"
lazy_static = "0.2"
#ignore = "0.2"

[dependencies.ignore]
path = "./ignore"
version = "0.2"

[lib]
path = "src/lib.rs"
name = "liboskar"

[[bin]]
path = "src/main.rs"
name = "sn"
