[package]
name = "file-sniffer"
version = "0.1.36-pre"
authors = ["Vanessa McHale <vamchale@gmail.com>"]
license-file = "LICENSE"
description = "Command-line tool to find build artifacts and junk on your computer."
readme = "README.md"
repository = "https://github.com/vmchale/file-sniffer"
documentation = "https://github.com/vmchale/file-sniffer#README"
homepage = "https://github.com/vmchale/file-sniffer" # consider hosting on http://vmchale.com/ ?

[profile.release]
lto = true

[features]
default = ["english"]
english = []
deutsch = []
francais = []

[dependencies]
nom = "3.0"
colored = "1.5"
clap = {version = "2.24", features = ["yaml"]}
regex = "0.2"
pad = "0.1"
lazy_static = "0.2"

#[dependencies.clap]
#git = "https://github.com/vmchale/clap-rs.git"
#rev = "b733f701bd9bf7e777281c596845da9d673a6d98"
#features = ["yaml"]

[lib]
path = "src/lib.rs"
name = "libsniff"

[[bin]]
path = "src/main.rs"
name = "sniff"
