[package]
name = "file-sniffer"
version = "1.3.4-pre"
authors = ["Vanessa McHale <vamchale@gmail.com>"]
license-file = "LICENSE"
description = "Command-line tool to find build artifacts and junk on your computer."
readme = "README.md"
repository = "https://github.com/vmchale/file-sniffer"
documentation = "https://github.com/vmchale/file-sniffer#README"
homepage = "https://github.com/vmchale/file-sniffer" # consider hosting on http://vmchale.com/ ?

build = "build.rs"

[build-dependencies]
clap = {version = "2.24", features = ["yaml"]}

[profile.release]
lto = true

[features]
default = ["english"]
english = []
deutsch = []
francais = []
bash = []
fish = []
verbose = []


[dependencies]
nom = "3.0"
colored = "1.5"
clap = {version = "2.24", features = ["yaml"]}
regex = "0.2"
pad = "0.1"
lazy_static = "0.2"
ignore = "0.2"

[lib]
path = "src/lib.rs"
name = "libsniff"

[[bin]]
required-features = ["english"]
path = "src/main.rs"
name = "sniff"

[[bin]]
required-features = ["francais"]
path = "src/main.rs"
name = "renifle"

[[bin]]
required-features = ["deutsch"]
path = "src/main.rs"
name = "schnüffle"
